services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - name=value
    volumes:
      - /usr/src/app/backend/node_modules
      - /usr/src/app/frontend/node_modules
    profiles:
      - production

volumes:
  mongodb_data: