services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
      - ./frontend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/your_database_name
      - PORT=3000
      - NODE_ENV=development
      - VITE_API_BASE_URL= #Frontend takes automatically the backend url when fetching data
      - FRONTEND_URL= 
    volumes:
      - /usr/src/app/backend/node_modules
      - /usr/src/app/frontend/node_modules
    profiles:
      - production
volumes:
  mongodb_data: