name: CI Pipeline

# Ejecuta el workflow en push o pull request a la rama main
on:
  pull_request:
    branches:
      - master

# Definimos el conjunto de jobs a ejecutar
jobs:
  # Job para el backend
  backend-tests:
    name: Run backend tests
    runs-on: ubuntu-latest

    # Definimos los pasos para ejecutar los tests del backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test

  # Job para el frontend
  frontend-tests:
    name: Run frontend tests
    runs-on: ubuntu-latest

    # Definimos los pasos para ejecutar los tests del frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
